### ISSUE TITLE
Getting this error (and I downloaded and reinstalled again) and am still getting this error

### ISSUE THREAD

**Issue by AJ1Stone** [jotunnlib/jotunnlib#37]
Message:WindSeeker.WindSeeker] Loaded Game VFX and SFX
[Error  :Jotunn.EventExtensions] System.MissingFieldException: Field 'StaticTarget.m_center' not found.
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in <87f5edfa58dd4ccba75b4848c29c2905>:0

**Comment by raduschirliu** [comment]
Hey, not sure if you've solved this or not, but this seems to be an issue with **Jotunn**, not **JotunnLib** (Naming is a bit confusing, I know :P). Please try reposting this issue on the [Jotunn](https://github.com/Valheim-Modding/Jotunn/issues) issues page instead. Also if possible, please include some more info about how/when the issue is happening, and what mods you have installed!
